name: Install and Deploy page
on:
  push:
    branches:
      - main

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.API_TOKEN }}
          publish_dir: ./src
          commit_message: ${{ github.event.head_commit.message }}
          cname: christofherkost.org
